title: Minería de Datos — CS
description: Curso interactivo de Minería de Datos aplicada a Ciencia de la Computación
baseurl: "/Data-Mining"
url: "https://ecuadros.github.io"
theme: null
markdown: kramdown
